using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using System.Windows;

namespace Aura
{
    /// <summary>
    /// Interaction logic for App.xaml
    /// </summary>
    public partial class App : Application
    {
        #region Variables
        public static string StartupPath { get; private set; }
        public static Dictionary<string, bool> HasWalls { get; set; }
        public static Dictionary<string, SpellData> SpellList { get; set; }

        #endregion
        public void Application_Startup(object sender, StartupEventArgs e)
        {
            // Create the startup window
            MainWindow wnd = new MainWindow();
            StartupPath = Environment.CurrentDirectory;
            // Do stuff here, e.g. to the window
            wnd.Title = "Aura";
            // Show the window
            wnd.Show();
        }

        #region Program

        //static Program()
        //{
        //    Spell.Cooldowns = new Dictionary<string, double>();
        //    Skill.Cooldowns = new Dictionary<string, double>();
        //    HasWalls = new Dictionary<string, bool>();
        //    StartupPath = AppDomain.CurrentDomain.BaseDirectory;
        //    Dictionary<string, SpellData> dictionary = new Dictionary<string, SpellData>(StringComparer.CurrentCultureIgnoreCase);
        //    string key1 = "Cat's Hearing";
        //    SpellData spellData1 = new SpellData("Cat's Hearing", 120, 5);
        //    dictionary.Add(key1, spellData1);
        //    string key2 = "srad lamh";
        //    SpellData spellData2 = new SpellData("srad lamh", 300, 1);
        //    dictionary.Add(key2, spellData2);
        //    string key3 = "athar lamh";
        //    SpellData spellData3 = new SpellData("athar lamh", 300, 1);
        //    dictionary.Add(key3, spellData3);
        //    string key4 = "beag srad lamh";
        //    SpellData spellData4 = new SpellData("beag srad lamh", 300, 1);
        //    dictionary.Add(key4, spellData4);
        //    string key5 = "beag athar lamh";
        //    SpellData spellData5 = new SpellData("beag athar lamh", 300, 1);
        //    dictionary.Add(key5, spellData5);
        //    string key6 = "Prevent Affliction";
        //    SpellData spellData6 = new SpellData("Prevent Affliction", 2000, 3);
        //    dictionary.Add(key6, spellData6);
        //    string key7 = "Increased Regeneration";
        //    SpellData spellData7 = new SpellData("Increased Regeneration", 5100, 5);
        //    dictionary.Add(key7, spellData7);
        //    string key8 = "Reflection";
        //    SpellData spellData8 = new SpellData("Reflection", 300, 8);
        //    dictionary.Add(key8, spellData8);
        //    string key9 = "mor dion comlha";
        //    SpellData spellData9 = new SpellData("mor dion comlha", 300, 4);
        //    dictionary.Add(key9, spellData9);
        //    string key10 = "mor dion";
        //    SpellData spellData10 = new SpellData("mor dion", 1000, 2);
        //    dictionary.Add(key10, spellData10);
        //    string key11 = "Stone Skin";
        //    SpellData spellData11 = new SpellData("Stone Skin", 1200, 0);
        //    dictionary.Add(key11, spellData11);
        //    string key12 = "Leafhopper Chirp";
        //    SpellData spellData12 = new SpellData("Leafhopper Chirp", 30, 0);
        //    dictionary.Add(key12, spellData12);
        //    string key13 = "deireas faileas";
        //    SpellData spellData13 = new SpellData("deireas faileas", 980, 3);
        //    dictionary.Add(key13, spellData13);
        //    string key14 = "mor deo searg gar";
        //    SpellData spellData14 = new SpellData("mor deo searg gar", 12000, 2);
        //    dictionary.Add(key14, spellData14);
        //    string key15 = "deo searg gar";
        //    SpellData spellData15 = new SpellData("deo searg gar", 8000, 4);
        //    dictionary.Add(key15, spellData15);
        //    string key16 = "ard deo searg";
        //    SpellData spellData16 = new SpellData("ard deo searg", 3000, 2);
        //    dictionary.Add(key16, spellData16);
        //    string key17 = "deo searg";
        //    SpellData spellData17 = new SpellData("deo searg", 1900, 4);
        //    dictionary.Add(key17, spellData17);
        //    string key18 = "deo saighead";
        //    SpellData spellData18 = new SpellData("deo saighead", 320, 2);
        //    dictionary.Add(key18, spellData18);
        //    string key19 = "deo lamh";
        //    SpellData spellData19 = new SpellData("deo lamh", 320, 1);
        //    dictionary.Add(key19, spellData19);
        //    string key20 = "ard cradh";
        //    SpellData spellData20 = new SpellData("ard cradh", 500, 3);
        //    dictionary.Add(key20, spellData20);
        //    string key21 = "mor cradh";
        //    SpellData spellData21 = new SpellData("mor cradh", 120, 3);
        //    dictionary.Add(key21, spellData21);
        //    string key22 = "cradh";
        //    SpellData spellData22 = new SpellData("cradh", 90, 3);
        //    dictionary.Add(key22, spellData22);
        //    string key23 = "beag cradh";
        //    SpellData spellData23 = new SpellData("beag cradh", 60, 2);
        //    dictionary.Add(key23, spellData23);
        //    string key24 = "ao dall";
        //    SpellData spellData24 = new SpellData("ao dall", 30, 1);
        //    dictionary.Add(key24, spellData24);
        //    string key25 = "ao puinsein";
        //    SpellData spellData25 = new SpellData("ao puinsein", 30, 1);
        //    dictionary.Add(key25, spellData25);
        //    string key26 = "ao suain";
        //    SpellData spellData26 = new SpellData("ao suain", 30, 1);
        //    dictionary.Add(key26, spellData26);
        //    string key27 = "ao ard cradh";
        //    SpellData spellData27 = new SpellData("ao ard cradh", 120, 1);
        //    dictionary.Add(key27, spellData27);
        //    string key28 = "ao mor cradh";
        //    SpellData spellData28 = new SpellData("ao mor cradh", 90, 1);
        //    dictionary.Add(key28, spellData28);
        //    string key29 = "ao cradh";
        //    SpellData spellData29 = new SpellData("ao cradh", 60, 1);
        //    dictionary.Add(key29, spellData29);
        //    string key30 = "ao beag cradh";
        //    SpellData spellData30 = new SpellData("ao beag cradh", 30, 1);
        //    dictionary.Add(key30, spellData30);
        //    string key31 = "breisleich";
        //    SpellData spellData31 = new SpellData("breisleich", 110, 1);
        //    dictionary.Add(key31, spellData31);
        //    string key32 = "beag puinsein";
        //    SpellData spellData32 = new SpellData("beag puinsein", 100, 4);
        //    dictionary.Add(key32, spellData32);
        //    string key33 = "puinsein";
        //    SpellData spellData33 = new SpellData("puinsein", 300, 3);
        //    dictionary.Add(key33, spellData33);
        //    string key34 = "beag pramh";
        //    SpellData spellData34 = new SpellData("beag pramh", 300, 4);
        //    dictionary.Add(key34, spellData34);
        //    string key35 = "pramh";
        //    SpellData spellData35 = new SpellData("pramh", 300, 4);
        //    dictionary.Add(key35, spellData35);
        //    string key36 = "suain";
        //    SpellData spellData36 = new SpellData("suain", 330, 4);
        //    dictionary.Add(key36, spellData36);
        //    string key37 = "dall";
        //    SpellData spellData37 = new SpellData("dall", 330, 4);
        //    dictionary.Add(key37, spellData37);
        //    string key38 = "beag naomh aite";
        //    SpellData spellData38 = new SpellData("beag naomh aite", 30, 3);
        //    dictionary.Add(key38, spellData38);
        //    string key39 = "naomh aite";
        //    SpellData spellData39 = new SpellData("naomh aite", 30, 2);
        //    dictionary.Add(key39, spellData39);
        //    string key40 = "mor naomh aite";
        //    SpellData spellData40 = new SpellData("mor naomh aite", 200, 4);
        //    dictionary.Add(key40, spellData40);
        //    string key41 = "ard naomh aite";
        //    SpellData spellData41 = new SpellData("ard naomh aite", 600, 4);
        //    dictionary.Add(key41, spellData41);
        //    string key42 = "ard ioc comlha";
        //    SpellData spellData42 = new SpellData("ard ioc comlha", 2100, 2);
        //    dictionary.Add(key42, spellData42);
        //    string key43 = "mor ioc comlha";
        //    SpellData spellData43 = new SpellData("mor ioc comlha", 1100, 2);
        //    dictionary.Add(key43, spellData43);
        //    string key44 = "ioc comlha";
        //    SpellData spellData44 = new SpellData("ioc comlha", 450, 2);
        //    dictionary.Add(key44, spellData44);
        //    string key45 = "beag ioc comlha";
        //    SpellData spellData45 = new SpellData("beag ioc comlha", 70, 1);
        //    dictionary.Add(key45, spellData45);
        //    string key46 = "nuadhaich";
        //    SpellData spellData46 = new SpellData("nuadhaich", 1260, 2);
        //    dictionary.Add(key46, spellData46);
        //    string key47 = "ard ioc";
        //    SpellData spellData47 = new SpellData("ard ioc", 800, 2);
        //    dictionary.Add(key47, spellData47);
        //    string key48 = "mor ioc";
        //    SpellData spellData48 = new SpellData("mor ioc", 600, 2);
        //    dictionary.Add(key48, spellData48);
        //    string key49 = "ioc";
        //    SpellData spellData49 = new SpellData("ioc", 200, 1);
        //    dictionary.Add(key49, spellData49);
        //    string key50 = "beag ioc";
        //    SpellData spellData50 = new SpellData("beag ioc", 30, 1);
        //    dictionary.Add(key50, spellData50);
        //    string key51 = "creag neart";
        //    SpellData spellData51 = new SpellData("creag neart", 30, 0);
        //    dictionary.Add(key51, spellData51);
        //    string key52 = "fas deireas";
        //    SpellData spellData52 = new SpellData("fas deireas", 30, 1);
        //    dictionary.Add(key52, spellData52);
        //    string key53 = "beannaich";
        //    SpellData spellData53 = new SpellData("beannaich", 30, 1);
        //    dictionary.Add(key53, spellData53);
        //    string key54 = "mor beannaich";
        //    SpellData spellData54 = new SpellData("mor beannaich", 90, 2);
        //    dictionary.Add(key54, spellData54);
        //    string key55 = "armachd";
        //    SpellData spellData55 = new SpellData("armachd", 30, 2);
        //    dictionary.Add(key55, spellData55);
        //    string key56 = "Dark Seal";
        //    SpellData spellData56 = new SpellData("Dark Seal", 350, 6);
        //    dictionary.Add(key56, spellData56);
        //    string key57 = "Darker Seal";
        //    SpellData spellData57 = new SpellData("Darker Seal", 450, 6);
        //    dictionary.Add(key57, spellData57);
        //    string key58 = "Mesmerize";
        //    SpellData spellData58 = new SpellData("Mesmerize", 800, 7);
        //    dictionary.Add(key58, spellData58);
        //    string key59 = "Cursed Tune 9";
        //    SpellData spellData59 = new SpellData("Cursed Tune 9", 3960, 0);
        //    dictionary.Add(key59, spellData59);
        //    string key60 = "Cursed Tune 8";
        //    SpellData spellData60 = new SpellData("Cursed Tune 8", 3960, 0);
        //    dictionary.Add(key60, spellData60);
        //    string key61 = "Cursed Tune 7";
        //    SpellData spellData61 = new SpellData("Cursed Tune 7", 3960, 0);
        //    dictionary.Add(key61, spellData61);
        //    string key62 = "Cursed Tune 6";
        //    SpellData spellData62 = new SpellData("Cursed Tune 6", 3960, 0);
        //    dictionary.Add(key62, spellData62);
        //    string key63 = "Cursed Tune 5";
        //    SpellData spellData63 = new SpellData("Cursed Tune 5", 3960, 0);
        //    dictionary.Add(key63, spellData63);
        //    string key64 = "Cursed Tune 4";
        //    SpellData spellData64 = new SpellData("Cursed Tune 4", 3960, 0);
        //    dictionary.Add(key64, spellData64);
        //    string key65 = "Cursed Tune 3";
        //    SpellData spellData65 = new SpellData("Cursed Tune 3", 3960, 0);
        //    dictionary.Add(key65, spellData65);
        //    string key66 = "Cursed Tune 2";
        //    SpellData spellData66 = new SpellData("Cursed Tune 2", 3960, 0);
        //    dictionary.Add(key66, spellData66);
        //    string key67 = "Cursed Tune 1";
        //    SpellData spellData67 = new SpellData("Cursed Tune 1", 3960, 0);
        //    dictionary.Add(key67, spellData67);
        //    string key68 = "puinneag spiorad";
        //    SpellData spellData68 = new SpellData("puinneag spiorad", 350, 2);
        //    dictionary.Add(key68, spellData68);
        //    string key69 = "ard puinneag spiorad";
        //    SpellData spellData69 = new SpellData("ard puinneag spiorad", 5, 0);
        //    dictionary.Add(key69, spellData69);
        //    string key70 = "Regeneration 7";
        //    SpellData spellData70 = new SpellData("Regeneration 7", 2720, 0);
        //    dictionary.Add(key70, spellData70);
        //    string key71 = "Regeneration 6";
        //    SpellData spellData71 = new SpellData("Regeneration 6", 2720, 0);
        //    dictionary.Add(key71, spellData71);
        //    string key72 = "Regeneration 5";
        //    SpellData spellData72 = new SpellData("Regeneration 5", 2720, 0);
        //    dictionary.Add(key72, spellData72);
        //    string key73 = "Regeneration 4";
        //    SpellData spellData73 = new SpellData("Regeneration 4", 2720, 0);
        //    dictionary.Add(key73, spellData73);
        //    string key74 = "Regeneration 3";
        //    SpellData spellData74 = new SpellData("Regeneration 3", 2720, 0);
        //    dictionary.Add(key74, spellData74);
        //    string key75 = "Regeneration 2";
        //    SpellData spellData75 = new SpellData("Regeneration 2", 2720, 0);
        //    dictionary.Add(key75, spellData75);
        //    string key76 = "Regeneration 1";
        //    SpellData spellData76 = new SpellData("Regeneration 1", 1220, 0);
        //    dictionary.Add(key76, spellData76);
        //    string key77 = "Counter Attack 8";
        //    SpellData spellData77 = new SpellData("Counter Attack 8", 3400, 2);
        //    dictionary.Add(key77, spellData77);
        //    string key78 = "Counter Attack 7";
        //    SpellData spellData78 = new SpellData("Counter Attack 7", 3400, 2);
        //    dictionary.Add(key78, spellData78);
        //    string key79 = "Counter Attack 6";
        //    SpellData spellData79 = new SpellData("Counter Attack 6", 3400, 2);
        //    dictionary.Add(key79, spellData79);
        //    string key80 = "Counter Attack 5";
        //    SpellData spellData80 = new SpellData("Counter Attack 5", 3400, 2);
        //    dictionary.Add(key80, spellData80);
        //    string key81 = "Counter Attack 4";
        //    SpellData spellData81 = new SpellData("Counter Attack 4", 2720, 2);
        //    dictionary.Add(key81, spellData81);
        //    string key82 = "Counter Attack 3";
        //    SpellData spellData82 = new SpellData("Counter Attack 3", 2720, 2);
        //    dictionary.Add(key82, spellData82);
        //    string key83 = "Counter Attack 2";
        //    SpellData spellData83 = new SpellData("Counter Attack 2", 2720, 2);
        //    dictionary.Add(key83, spellData83);
        //    string key84 = "Counter Attack 1";
        //    SpellData spellData84 = new SpellData("Counter Attack 1", 2720, 2);
        //    dictionary.Add(key84, spellData84);
        //    string key85 = "ard srad";
        //    SpellData spellData85 = new SpellData("ard srad", 2530, 4);
        //    dictionary.Add(key85, spellData85);
        //    string key86 = "ard sal";
        //    SpellData spellData86 = new SpellData("ard sal", 2530, 4);
        //    dictionary.Add(key86, spellData86);
        //    string key87 = "ard creag";
        //    SpellData spellData87 = new SpellData("ard creag", 2530, 4);
        //    dictionary.Add(key87, spellData87);
        //    string key88 = "ard athar";
        //    SpellData spellData88 = new SpellData("ard athar", 2530, 4);
        //    dictionary.Add(key88, spellData88);
        //    string key89 = "Unholy Explosion";
        //    SpellData spellData89 = new SpellData("Unholy Explosion", 5500, 2);
        //    dictionary.Add(key89, spellData89);
        //    string key90 = "mor strioch pian gar";
        //    SpellData spellData90 = new SpellData("mor strioch pian gar", 500, 1);
        //    dictionary.Add(key90, spellData90);
        //    string key91 = "pian na dion";
        //    SpellData spellData91 = new SpellData("pian na dion", 1500, 1);
        //    dictionary.Add(key91, spellData91);
        //    string key92 = "mor pian na dion";
        //    SpellData spellData92 = new SpellData("mor pian na dion", 3000, 1);
        //    dictionary.Add(key92, spellData92);
        //    string key93 = "Wings of Protection";
        //    SpellData spellData93 = new SpellData("Wings of Protection", 900, 0);
        //    dictionary.Add(key93, spellData93);
        //    string key94 = "Lyliac Plant";
        //    SpellData spellData94 = new SpellData("Lyliac Plant", 1000, 0);
        //    dictionary.Add(key94, spellData94);
        //    string key95 = "Lyliac Vineyard";
        //    SpellData spellData95 = new SpellData("Lyliac Vineyard", 1000, 0);
        //    dictionary.Add(key95, spellData95);
        //    string key96 = "fas spiorad";
        //    SpellData spellData96 = new SpellData("fas spiorad", 0, 8);
        //    dictionary.Add(key96, spellData96);
        //    string key97 = "beag fas nadur";
        //    SpellData spellData97 = new SpellData("beag fas nadur", 35, 2);
        //    dictionary.Add(key97, spellData97);
        //    string key98 = "fas nadur";
        //    SpellData spellData98 = new SpellData("fas nadur", 35, 2);
        //    dictionary.Add(key98, spellData98);
        //    string key99 = "mor fas nadur";
        //    SpellData spellData99 = new SpellData("mor fas nadur", 150, 4);
        //    dictionary.Add(key99, spellData99);
        //    string key100 = "ard fas nadur";
        //    SpellData spellData100 = new SpellData("ard fas nadur", 1000, 8);
        //    dictionary.Add(key100, spellData100);
        //    string key101 = "Disenchanter";
        //    SpellData spellData101 = new SpellData("Disenchanter", 3000, 4);
        //    dictionary.Add(key101, spellData101);
        //    string key102 = "Bubble Block";
        //    SpellData spellData102 = new SpellData("Bubble Block", 700, 0);
        //    dictionary.Add(key102, spellData102);
        //    string key103 = "Mud Wall";
        //    SpellData spellData103 = new SpellData("Mud Wall", 700, 0);
        //    dictionary.Add(key103, spellData103);
        //    string key104 = "Cyclone";
        //    SpellData spellData104 = new SpellData("Cyclone", 1200, 0);
        //    dictionary.Add(key104, spellData104);
        //    string key105 = "Fiery Defender";
        //    SpellData spellData105 = new SpellData("Fiery Defender", 3000, 4);
        //    dictionary.Add(key105, spellData105);
        //    string key106 = "Keeter 12";
        //    SpellData spellData106 = new SpellData("Keeter 12", 2800, 2);
        //    dictionary.Add(key106, spellData106);
        //    string key107 = "Keeter 11";
        //    SpellData spellData107 = new SpellData("Keeter 11", 2800, 2);
        //    dictionary.Add(key107, spellData107);
        //    string key108 = "Keeter 10";
        //    SpellData spellData108 = new SpellData("Keeter 10", 2800, 2);
        //    dictionary.Add(key108, spellData108);
        //    string key109 = "Keeter 9";
        //    SpellData spellData109 = new SpellData("Keeter 9", 2800, 2);
        //    dictionary.Add(key109, spellData109);
        //    string key110 = "Keeter 8";
        //    SpellData spellData110 = new SpellData("Keeter 8", 2800, 2);
        //    dictionary.Add(key110, spellData110);
        //    string key111 = "Keeter 7";
        //    SpellData spellData111 = new SpellData("Keeter 7", 2800, 2);
        //    dictionary.Add(key111, spellData111);
        //    string key112 = "Keeter 6";
        //    SpellData spellData112 = new SpellData("Keeter 6", 2800, 2);
        //    dictionary.Add(key112, spellData112);
        //    string key113 = "Keeter 5";
        //    SpellData spellData113 = new SpellData("Keeter 5", 2800, 2);
        //    dictionary.Add(key113, spellData113);
        //    string key114 = "Keeter 4";
        //    SpellData spellData114 = new SpellData("Keeter 4", 2800, 2);
        //    dictionary.Add(key114, spellData114);
        //    string key115 = "Keeter 3";
        //    SpellData spellData115 = new SpellData("Keeter 3", 2800, 2);
        //    dictionary.Add(key115, spellData115);
        //    string key116 = "Keeter 2";
        //    SpellData spellData116 = new SpellData("Keeter 2", 2800, 2);
        //    dictionary.Add(key116, spellData116);
        //    string key117 = "Keeter 1";
        //    SpellData spellData117 = new SpellData("Keeter 1", 2800, 2);
        //    dictionary.Add(key117, spellData117);
        //    string key118 = "Groo 12";
        //    SpellData spellData118 = new SpellData("Groo 12", 2800, 2);
        //    dictionary.Add(key118, spellData118);
        //    string key119 = "Groo 11";
        //    SpellData spellData119 = new SpellData("Groo 11", 2800, 2);
        //    dictionary.Add(key119, spellData119);
        //    string key120 = "Groo 10";
        //    SpellData spellData120 = new SpellData("Groo 10", 2800, 2);
        //    dictionary.Add(key120, spellData120);
        //    string key121 = "Groo 9";
        //    SpellData spellData121 = new SpellData("Groo 9", 2800, 2);
        //    dictionary.Add(key121, spellData121);
        //    string key122 = "Groo 8";
        //    SpellData spellData122 = new SpellData("Groo 8", 2800, 2);
        //    dictionary.Add(key122, spellData122);
        //    string key123 = "Groo 7";
        //    SpellData spellData123 = new SpellData("Groo 7", 2800, 2);
        //    dictionary.Add(key123, spellData123);
        //    string key124 = "Groo 6";
        //    SpellData spellData124 = new SpellData("Groo 6", 2800, 2);
        //    dictionary.Add(key124, spellData124);
        //    string key125 = "Groo 5";
        //    SpellData spellData125 = new SpellData("Groo 5", 2800, 2);
        //    dictionary.Add(key125, spellData125);
        //    string key126 = "Groo 4";
        //    SpellData spellData126 = new SpellData("Groo 4", 2800, 2);
        //    dictionary.Add(key126, spellData126);
        //    string key127 = "Groo 3";
        //    SpellData spellData127 = new SpellData("Groo 3", 2800, 2);
        //    dictionary.Add(key127, spellData127);
        //    string key128 = "Groo 2";
        //    SpellData spellData128 = new SpellData("Groo 2", 2800, 2);
        //    dictionary.Add(key128, spellData128);
        //    string key129 = "Groo 1";
        //    SpellData spellData129 = new SpellData("Groo 1", 2800, 2);
        //    dictionary.Add(key129, spellData129);
        //    string key130 = "Mermaid 12";
        //    SpellData spellData130 = new SpellData("Mermaid 12", 2800, 2);
        //    dictionary.Add(key130, spellData130);
        //    string key131 = "Mermaid 11";
        //    SpellData spellData131 = new SpellData("Mermaid 11", 2800, 2);
        //    dictionary.Add(key131, spellData131);
        //    string key132 = "Mermaid 10";
        //    SpellData spellData132 = new SpellData("Mermaid 10", 2800, 2);
        //    dictionary.Add(key132, spellData132);
        //    string key133 = "Mermaid 9";
        //    SpellData spellData133 = new SpellData("Mermaid 9", 2800, 2);
        //    dictionary.Add(key133, spellData133);
        //    string key134 = "Mermaid 8";
        //    SpellData spellData134 = new SpellData("Mermaid 8", 2800, 2);
        //    dictionary.Add(key134, spellData134);
        //    string key135 = "Mermaid 7";
        //    SpellData spellData135 = new SpellData("Mermaid 7", 2800, 2);
        //    dictionary.Add(key135, spellData135);
        //    string key136 = "Mermaid 6";
        //    SpellData spellData136 = new SpellData("Mermaid 6", 2800, 2);
        //    dictionary.Add(key136, spellData136);
        //    string key137 = "Mermaid 5";
        //    SpellData spellData137 = new SpellData("Mermaid 5", 2800, 2);
        //    dictionary.Add(key137, spellData137);
        //    string key138 = "Mermaid 4";
        //    SpellData spellData138 = new SpellData("Mermaid 4", 2800, 2);
        //    dictionary.Add(key138, spellData138);
        //    string key139 = "Mermaid 3";
        //    SpellData spellData139 = new SpellData("Mermaid 3", 2800, 2);
        //    dictionary.Add(key139, spellData139);
        //    string key140 = "Mermaid 2";
        //    SpellData spellData140 = new SpellData("Mermaid 2", 2800, 2);
        //    dictionary.Add(key140, spellData140);
        //    string key141 = "Mermaid 1";
        //    SpellData spellData141 = new SpellData("Mermaid 1", 2800, 2);
        //    dictionary.Add(key141, spellData141);
        //    string key142 = "Torch 12";
        //    SpellData spellData142 = new SpellData("Torch 12", 2800, 2);
        //    dictionary.Add(key142, spellData142);
        //    string key143 = "Torch 11";
        //    SpellData spellData143 = new SpellData("Torch 11", 2800, 2);
        //    dictionary.Add(key143, spellData143);
        //    string key144 = "Torch 10";
        //    SpellData spellData144 = new SpellData("Torch 10", 2800, 2);
        //    dictionary.Add(key144, spellData144);
        //    string key145 = "Torch 9";
        //    SpellData spellData145 = new SpellData("Torch 9", 2800, 2);
        //    dictionary.Add(key145, spellData145);
        //    string key146 = "Torch 8";
        //    SpellData spellData146 = new SpellData("Torch 8", 2800, 2);
        //    dictionary.Add(key146, spellData146);
        //    string key147 = "Torch 7";
        //    SpellData spellData147 = new SpellData("Torch 7", 2800, 2);
        //    dictionary.Add(key147, spellData147);
        //    string key148 = "Torch 6";
        //    SpellData spellData148 = new SpellData("Torch 6", 2800, 2);
        //    dictionary.Add(key148, spellData148);
        //    string key149 = "Torch 5";
        //    SpellData spellData149 = new SpellData("Torch 5", 2800, 2);
        //    dictionary.Add(key149, spellData149);
        //    string key150 = "Torch 4";
        //    SpellData spellData150 = new SpellData("Torch 4", 2800, 2);
        //    dictionary.Add(key150, spellData150);
        //    string key151 = "Torch 3";
        //    SpellData spellData151 = new SpellData("Torch 3", 2800, 2);
        //    dictionary.Add(key151, spellData151);
        //    string key152 = "Torch 2";
        //    SpellData spellData152 = new SpellData("Torch 2", 2800, 2);
        //    dictionary.Add(key152, spellData152);
        //    string key153 = "Torch 1";
        //    SpellData spellData153 = new SpellData("Torch 1", 2800, 2);
        //    dictionary.Add(key153, spellData153);
        //    string key154 = "Mist";
        //    SpellData spellData154 = new SpellData("Mist", 60, 0);
        //    dictionary.Add(key154, spellData154);
        //    string key155 = "dion";
        //    SpellData spellData155 = new SpellData("dion", 600, 0);
        //    dictionary.Add(key155, spellData155);
        //    string key156 = "Howl";
        //    SpellData spellData156 = new SpellData("Howl", 360, 1);
        //    dictionary.Add(key156, spellData156);
        //    string key157 = "Wraith's Touch";
        //    SpellData spellData157 = new SpellData("Wraith's Touch", 1420, 4);
        //    dictionary.Add(key157, spellData157);
        //    string key158 = "Komodas Form";
        //    SpellData spellData158 = new SpellData("Komodas Form", 360, 0);
        //    dictionary.Add(key158, spellData158);
        //    string key159 = "Wild Komodas Form";
        //    SpellData spellData159 = new SpellData("Wild Komodas Form", 360, 0);
        //    dictionary.Add(key159, spellData159);
        //    string key160 = "Fierce Komodas Form";
        //    SpellData spellData160 = new SpellData("Fierce Komodas Form", 360, 0);
        //    dictionary.Add(key160, spellData160);
        //    string key161 = "Master Komodas Form";
        //    SpellData spellData161 = new SpellData("Master Komodas Form", 360, 0);
        //    dictionary.Add(key161, spellData161);
        //    string key162 = "Feral Form";
        //    SpellData spellData162 = new SpellData("Feral Form", 360, 0);
        //    dictionary.Add(key162, spellData162);
        //    string key163 = "Wild Feral Form";
        //    SpellData spellData163 = new SpellData("Wild Feral Form", 360, 0);
        //    dictionary.Add(key163, spellData163);
        //    string key164 = "Fierce Feral Form";
        //    SpellData spellData164 = new SpellData("Fierce Feral Form", 360, 0);
        //    dictionary.Add(key164, spellData164);
        //    string key165 = "Master Feral Form";
        //    SpellData spellData165 = new SpellData("Master Feral Form", 360, 0);
        //    dictionary.Add(key165, spellData165);
        //    string key166 = "Karura Form";
        //    SpellData spellData166 = new SpellData("Karura Form", 360, 0);
        //    dictionary.Add(key166, spellData166);
        //    string key167 = "Wild Karura Form";
        //    SpellData spellData167 = new SpellData("Wild Karura Form", 360, 0);
        //    dictionary.Add(key167, spellData167);
        //    string key168 = "Fierce Karura Form";
        //    SpellData spellData168 = new SpellData("Fierce Karura Form", 360, 0);
        //    dictionary.Add(key168, spellData168);
        //    string key169 = "Master Karura Form";
        //    SpellData spellData169 = new SpellData("Master Karura Form", 360, 0);
        //    dictionary.Add(key169, spellData169);
        //    string key170 = "Cold Blood";
        //    SpellData spellData170 = new SpellData("Cold Blood", 1420, 1);
        //    dictionary.Add(key170, spellData170);
        //    string key171 = "Hail of Feathers 1";
        //    SpellData spellData171 = new SpellData("Hail of Feathers 1", 1420, 0);
        //    dictionary.Add(key171, spellData171);
        //    string key172 = "Hail of Feathers 2";
        //    SpellData spellData172 = new SpellData("Hail of Feathers 2", 760, 0);
        //    dictionary.Add(key172, spellData172);
        //    string key173 = "Hail of Feathers 3";
        //    SpellData spellData173 = new SpellData("Hail of Feathers 3", 760, 0);
        //    dictionary.Add(key173, spellData173);
        //    string key174 = "Hail of Feathers 4";
        //    SpellData spellData174 = new SpellData("Hail of Feathers 4", 1420, 0);
        //    dictionary.Add(key174, spellData174);
        //    string key175 = "Hail of Feathers 5";
        //    SpellData spellData175 = new SpellData("Hail of Feathers 5", 1420, 0);
        //    dictionary.Add(key175, spellData175);
        //    string key176 = "Hail of Feathers 6";
        //    SpellData spellData176 = new SpellData("Hail of Feathers 6", 1420, 0);
        //    dictionary.Add(key176, spellData176);
        //    string key177 = "Hail of Feathers 7";
        //    SpellData spellData177 = new SpellData("Hail of Feathers 7", 1420, 0);
        //    dictionary.Add(key177, spellData177);
        //    string key178 = "White Bat Stance";
        //    SpellData spellData178 = new SpellData("White Bat Stance", 25, 0);
        //    dictionary.Add(key178, spellData178);
        //    string key179 = "Draco Stance";
        //    SpellData spellData179 = new SpellData("Draco Stance", 200, 0);
        //    dictionary.Add(key179, spellData179);
        //    string key180 = "Iron Skin";
        //    SpellData spellData180 = new SpellData("Iron Skin", 250, 2);
        //    dictionary.Add(key180, spellData180);
        //    string key181 = "asgall faileas";
        //    SpellData spellData181 = new SpellData("asgall faileas", 310, 1);
        //    dictionary.Add(key181, spellData181);
        //    string key182 = "Aegis Sphere";
        //    SpellData spellData182 = new SpellData("Aegis Sphere", 5000, 0);
        //    dictionary.Add(key182, spellData182);
        //    string key183 = "Hide";
        //    SpellData spellData183 = new SpellData("Hide", 200, 0);
        //    dictionary.Add(key183, spellData183);
        //    string key184 = "Shock Arrow";
        //    SpellData spellData184 = new SpellData("Shock Arrow", 1000, 0);
        //    dictionary.Add(key184, spellData184);
        //    string key185 = "Life Arrow";
        //    SpellData spellData185 = new SpellData("Life Arrow", 1500, 0);
        //    dictionary.Add(key185, spellData185);
        //    string key186 = "Star Arrow 10";
        //    SpellData spellData186 = new SpellData("Star Arrow 10", 1360, 0);
        //    dictionary.Add(key186, spellData186);
        //    string key187 = "Star Arrow 9";
        //    SpellData spellData187 = new SpellData("Star Arrow 9", 775, 0);
        //    dictionary.Add(key187, spellData187);
        //    string key188 = "Star Arrow 8";
        //    SpellData spellData188 = new SpellData("Star Arrow 8", 775, 0);
        //    dictionary.Add(key188, spellData188);
        //    string key189 = "Star Arrow 7";
        //    SpellData spellData189 = new SpellData("Star Arrow 7", 775, 0);
        //    dictionary.Add(key189, spellData189);
        //    string key190 = "Star Arrow 6";
        //    SpellData spellData190 = new SpellData("Star Arrow 6", 775, 0);
        //    dictionary.Add(key190, spellData190);
        //    string key191 = "Star Arrow 5";
        //    SpellData spellData191 = new SpellData("Star Arrow 5", 475, 0);
        //    dictionary.Add(key191, spellData191);
        //    string key192 = "Star Arrow 4";
        //    SpellData spellData192 = new SpellData("Star Arrow 4", 475, 0);
        //    dictionary.Add(key192, spellData192);
        //    string key193 = "Star Arrow 3";
        //    SpellData spellData193 = new SpellData("Star Arrow 3", 475, 0);
        //    dictionary.Add(key193, spellData193);
        //    string key194 = "Star Arrow 2";
        //    SpellData spellData194 = new SpellData("Star Arrow 2", 475, 0);
        //    dictionary.Add(key194, spellData194);
        //    string key195 = "Star Arrow 1";
        //    SpellData spellData195 = new SpellData("Star Arrow 1", 400, 0);
        //    dictionary.Add(key195, spellData195);
        //    string key196 = "Frost Arrow 6";
        //    SpellData spellData196 = new SpellData("Frost Arrow 6", 800, 1);
        //    dictionary.Add(key196, spellData196);
        //    string key197 = "Frost Arrow 5";
        //    SpellData spellData197 = new SpellData("Frost Arrow 5", 800, 1);
        //    dictionary.Add(key197, spellData197);
        //    string key198 = "Frost Arrow 4";
        //    SpellData spellData198 = new SpellData("Frost Arrow 4", 800, 1);
        //    dictionary.Add(key198, spellData198);
        //    string key199 = "Frost Arrow 3";
        //    SpellData spellData199 = new SpellData("Frost Arrow 3", 800, 1);
        //    dictionary.Add(key199, spellData199);
        //    string key200 = "Frost Arrow 2";
        //    SpellData spellData200 = new SpellData("Frost Arrow 2", 700, 1);
        //    dictionary.Add(key200, spellData200);
        //    string key201 = "Frost Arrow 1";
        //    SpellData spellData201 = new SpellData("Frost Arrow 1", 700, 1);
        //    dictionary.Add(key201, spellData201);
        //    string key202 = "Supernova Shot";
        //    SpellData spellData202 = new SpellData("Supernova Shot", 1500, 0);
        //    dictionary.Add(key202, spellData202);
        //    string key203 = "mor athar";
        //    SpellData spellData203 = new SpellData("mor athar", 800, 4);
        //    dictionary.Add(key203, spellData203);
        //    string key204 = "mor creag";
        //    SpellData spellData204 = new SpellData("mor creag", 800, 4);
        //    dictionary.Add(key204, spellData204);
        //    string key205 = "mor srad";
        //    SpellData spellData205 = new SpellData("mor srad", 800, 4);
        //    dictionary.Add(key205, spellData205);
        //    string key206 = "mor sal";
        //    SpellData spellData206 = new SpellData("mor sal", 800, 4);
        //    dictionary.Add(key206, spellData206);
        //    SpellList = dictionary;
        //}

        #endregion


        [STAThread]
        public static void Main(string[] args)
        {
            App app = new App();
            app.InitializeComponent();
            //Settings.Load();
            //Settings.Save();
            app.Run();
        }
    }
}
